# Generated by Django 4.2.16 on 2024-11-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qpdb_app', '0002_set'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('date', models.DateTimeField(blank=True)),
            ],
        ),
    ]
