# Generated by Django 4.2.16 on 2024-11-07 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qpdb_app', '0003_performance'),
    ]

    operations = [
        migrations.CreateModel(
            name='TuneSetRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qpdb_app.set')),
                ('tune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qpdb_app.tune')),
            ],
            options={
                'verbose_name': 'Tune-Set Relationship',
            },
        ),
    ]
