# Generated by Django 4.2.16 on 2024-11-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qpdb_app', '0004_tunesetrelationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='tunesetrelationship',
            name='position',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
