# Generated by Django 4.2.16 on 2024-11-07 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qpdb_app', '0005_tunesetrelationship_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetPerformanceRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qpdb_app.performance')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qpdb_app.set')),
            ],
            options={
                'verbose_name': 'Set-Performance Relationship',
            },
        ),
    ]
