# Generated by Django 4.2.16 on 2024-11-22 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qpdb_app', '0007_alter_setperformancerelationship_performance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedleyPerformanceRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Medley-Performance Relationship',
            },
        ),
        migrations.CreateModel(
            name='TuneMedleyRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Tune-Medley Relationship',
            },
        ),
        migrations.RemoveField(
            model_name='tunesetrelationship',
            name='set',
        ),
        migrations.RemoveField(
            model_name='tunesetrelationship',
            name='tune',
        ),
        migrations.RenameModel(
            old_name='Set',
            new_name='Medley',
        ),
        migrations.DeleteModel(
            name='SetPerformanceRelationship',
        ),
        migrations.DeleteModel(
            name='TuneSetRelationship',
        ),
        migrations.AddField(
            model_name='tunemedleyrelationship',
            name='medley',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qpdb_app.medley'),
        ),
        migrations.AddField(
            model_name='tunemedleyrelationship',
            name='tune',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qpdb_app.tune'),
        ),
        migrations.AddField(
            model_name='medleyperformancerelationship',
            name='medley',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qpdb_app.medley'),
        ),
        migrations.AddField(
            model_name='medleyperformancerelationship',
            name='performance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qpdb_app.performance'),
        ),
    ]
